# Generated by Django 4.0.3 on 2022-03-28 20:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimage",
            name="image",
            field=models.ImageField(upload_to=core.models.upload_location),
        ),
    ]
