# Generated by Django 4.0.3 on 2022-03-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dmsfront", "0002_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=150)),
                ("event_date", models.DateTimeField()),
                ("event_location", models.TextField()),
                ("event_description", models.TextField()),
                ("available_seats", models.PositiveSmallIntegerField()),
                ("host_name", models.CharField(max_length=100)),
                ("host_details", models.CharField(max_length=250)),
            ],
        ),
    ]
