# Generated by Django 4.0.3 on 2022-04-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dmsfront",
            "0005_alter_timesheet_end_time_alter_timesheet_start_time",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="end_time",
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="start_time",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
