# Generated by Django 4.0.3 on 2022-04-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dmsfront",
            "0006_alter_timesheet_end_time_alter"
            "_timesheet_start_time_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="timesheet",
            old_name="end_time",
            new_name="end",
        ),
        migrations.RenameField(
            model_name="timesheet",
            old_name="start_time",
            new_name="start",
        ),
    ]
